apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cw-opensearch-operator-2-7-0
  namespace: argocd
spec:
  project: cw-opensearch-operator
  sources:
    - path: ""
      repoURL: http://chartmuseum.chartmuseum.svc.cluster.local:8080
      targetRevision: 2.7.0
      chart: opensearch-operator
      helm:
        valueFiles:
          - $config-values/DEV/OS/values/opensearch-operator.yaml
    - path: ""
      repoURL: https://github.com/bl4ckb1rd77/helm-charts.git
      targetRevision: main
      ref: "config-values"
  destination:
    server: https://kubernetes.default.svc
    namespace: cw-opensearch-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
