apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cw-opensearch-operator
  namespace: argocd
spec:
  project: cw-opensearch-operator
  source:
    repoURL: http://chartmuseum.chartmuseum.svc.cluster.local:8080
    targetRevision: 2.7.0
    chart: opensearch-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: cw-opensearch-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
