apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cw-opensearch-operator
  namespace: argocd
spec:
  project: cw-opensearch-operator
  destination:
    namespace: "cw-opensearch-operator"
    name: "in-cluster"
  syncPolicy:
    # nothing automated
  sources:
    - repoURL: "http://chartmuseum.chartmuseum.svc.cluster.local:8080/api/charts"
      targetRevision: 2.7.0
      path: ""
      chart: opensearch-operator
      helm:
        valueFiles:
          - $config-values/DEV/OS/values/opensearch-operator.yaml
    - repoURL: "https://github.com/bl4ckb1rd77/helm-charts.git"
      targetRevision: main
      ref: "config-values"
