apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-datenhaus-index
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: dev-datenhaus-index
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
