apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init-namespace
  namespace: argocd
spec:
  project: init-namespace
  destination:
    name: "in-cluster"
    namespace: "init-namespace"
  sources:
    - repoURL: "https://github.com/bl4ckb1rd77/helm-charts.git"
      targetRevision: main
      path: "./NS-INIT/manifest"
      directory:
        recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
